### ISSUE TITLE
don't connect to mongo localhost

### ISSUE THREAD

**Issue by tiamo405** [mongodb-js/mongodb-mcp-server#295]
i use command: docker run --rm -i \
  -e MDB_MCP_CONNECTION_STRING="mongodb+srv://username:password@cluster.mongodb.net/myDatabase" \
  mongodb/mongodb-mcp-server:latest

I use docker to build mongo without username and password. So how should I connect mongo, I want to use docker to run

**Comment by fmenezes** [comment]
@tiamo405 thanks for reporting this. From your comment I think you're lauching mongodb via `docker run ... mongo` + `docker run --rm -i
-e MDB_MCP_CONNECTION_STRING="mongodb+srv://username:password@cluster.mongodb.net/myDatabase"
mongodb/mongodb-mcp-server:latest`, correct?

If that is the case you might need to make sure both containers are part of the same virtual network and use a local ip like `docker run --rm -i --network customNet
-e MDB_MCP_CONNECTION_STRING="mongodb://10.x.x.x/myDatabase"
mongodb/mongodb-mcp-server:latest`.

You can read more about it in https://docs.docker.com/engine/network/

**Comment by tiamo405** [comment]
> [@tiamo405](https://github.com/tiamo405) thanks for reporting this. From your comment I think you're lauching mongodb via `docker run ... mongo` + `docker run --rm -i -e MDB_MCP_CONNECTION_STRING="mongodb+srv://username:password@cluster.mongodb.net/myDatabase" mongodb/mongodb-mcp-server:latest`, correct?
> 
> If that is the case you might need to make sure both containers are part of the same virtual network and use a local ip like `docker run --rm -i --network customNet -e MDB_MCP_CONNECTION_STRING="mongodb://10.x.x.x/myDatabase" mongodb/mongodb-mcp-server:latest`.
> 
> You can read more about it in https://docs.docker.com/engine/network/

i will try again, thanks

**Comment by jleonelion** [comment]
@tiamo405 hope you had success with this.  I wanted to post something I did to get the mongo MCP connected to a MongoDB instance that I have running locally in the docker image: mongodb/mongodb-community-server:latest 

# Define MongoDB service and network
I created a docker-compose yml to launch the mongodb container locally
```yaml
services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    # expose mongo port locally to connect using Compass or other tools
    ports:
      - "27017:27017"
    # define volums for mongo data persistence
    volumes:
      - ~/mongodb/data:/data/db
    # reference the docker network to allow communication between containers
    networks:
      - mongodb-network
    # healthcheck to ensure MongoDB is running before other services try to connect
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "\"db.adminCommand('ping')\""]
      interval: 5s
      timeout: 5s
      retries: 10
networks:
  mongodb-network:
    driver: bridge
```
# Launch MongoDB service and network
From directory where docker-compose.yml is located `docker compose up`

# Identify the Docker network
The network name will typically include the name of directory hosting docker-compose.yml so need to confirm the name by running `docker network ls --filter name=mongodb-network`
In my case, docker-compose was in a directory called `collection-manager` so the network was `collection-manager_mongodb-network`

# Launch MongoMCP server in the docker network
`docker run -i --rm -e MDB_MCP_CONNECTION_STRING=mongodb://<user>:<password>@mongodb:27017/<database>" --network <network> mongodb/mongodb-mcp-server:latest`
Obviously you need to update the connection string with appropriate values for `<user>`, `<password>`, `<database>`, and `<network>`
