### ISSUE TITLE
[Bug]: TypeError: connectionString.startsWith is not a function

### ISSUE THREAD

**Issue by ImoutoChan** [mongodb-js/mongodb-mcp-server#327]
### Version

mcp/mongodb@sha256:44eed0f93b85db457e86d9a7de44aa032d6d9128aac05086194402adc4e2a9b7

### App

- [ ] Cursor
- [ ] Windsurf
- [ ] VSCode
- [ ] VSCode Insiders
- [ ] Claude Desktop
- [x] Other

### Affected Models (if applicable)

- [ ] Claude 3.5 Sonnet
- [ ] Claude 3.7 Sonnet
- [ ] GPT-4a
- [ ] o4-mini
- [ ] Other

### Bug Description

I'm trying to use docker desktop feature MCP Tools: https://docs.docker.com/ai/mcp-catalog-and-toolkit/toolkit/, 
I installed mongodb and provided it with my connection string.

However, when I run `docker mcp gateway run` I get

```
docker mcp gateway run
- Those servers are enabled: mongodb
- Using images:
  - mcp/mongodb@sha256:44eed0f93b85db457e86d9a7de44aa032d6d9128aac05086194402adc4e2a9b7
- Pulling images [mcp/mongodb]
> Images pulled in 3.912ms
- Listing MCP tools...
  - Running server mcp/mongodb with [run --rm -i --init --security-opt no-new-privileges --cpus 1 --memory 2Gb --pull never --label docker-mcp=true --label docker-mcp-tool-type=mcp --label docker-mcp-name=mongodb --label docker-mcp-transport=stdio -e MDB_MCP_CONNECTION_STRING]
  > Can't start mongodb: initializing mcp/mongodb@sha256:44eed0f93b85db457e86d9a7de44aa032d6d9128aac05086194402adc4e2a9b7: Failed to connect to MongoDB instance using the connection string from the config:  TypeError: connectionString.startsWith is not a function
    at connectionStringHasValidScheme (/usr/local/lib/node_modules/mongodb-mcp-server/node_modules/mongodb-connection-string-url/lib/index.js:9:30)
    at new ConnectionString (/usr/local/lib/node_modules/mongodb-mcp-server/node_modules/mongodb-connection-string-url/lib/index.js:85:34)
    at setAppNameParamIfMissing (file:///usr/local/lib/node_modules/mongodb-mcp-server/dist/helpers/connectionOptions.js:3:33)
    at Session.connectToMongoDB (file:///usr/local/lib/node_modules/mongodb-mcp-server/dist/session.js:66:28)
    at Server.validateConfig (file:///usr/local/lib/node_modules/mongodb-mcp-server/dist/server.js:121:36)
    at Server.connect (file:///usr/local/lib/node_modules/mongodb-mcp-server/dist/server.js:49:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async file:///usr/local/lib/node_modules/mongodb-mcp-server/dist/index.js:45:5
```

**Comment by himanshusinghs** [comment]
Hi @ImoutoChan! From the error it looks like the provided connection string is anything but a string, very likely getting resolved to some JS object. Can you check and confirm if the environment variable `MDB_MCP_CONNECTION_STRING` is being provided correctly or not, a string?

**Comment by schnz** [comment]
I also experienced this issue with the latest Docker image (0.2.0). By the looks of it, the connection string must not contain multiple hosts, as is the case when running multiple shards. Restricting the connection string to a single shard is working, though.

**Comment by kmruiz** [comment]
Hey @schnz, @ImoutoChan , thanks for the information!

@schnz, have you tested the same connection string in mongosh? Does it work for you or fails with the same issue?

The issue seems to be bubbling from this line of code: https://github.com/mongodb-js/mongodb-connection-string-url/blob/main/src/index.ts#L132 and  the `connectToMongoDB` we have in session.ts.

**Comment by schnz** [comment]
@kmruiz  Yes, just tested it with `mongosh` and it works. Also MongoDB compass and mongoose work fine with it.

Tested with a connection string like this:
`mongodb://user:password@shard-00-00.somehost.tld:27017,shard-00-01.somehost.tld:27017,shard-00-02.somehost.tld:27017/somedb?ssl=true&replicaSet=shard-0&authSource=admin&retryWrites=true&w=majority`

Where as the MCP server requires this:
`mongodb://user:password@shard-00-00.somehost.tld:27017/somedb?ssl=true&replicaSet=test-shard-0&authSource=admin&retryWrites=true&w=majority`

Edit:
For reference, this is my `compose.yml` (which works this way, but leads to the error mentioned in the opening post as soon as I specify multiple hosts
```
services:
  mongodb:
    container_name: mongodb-mcp
    image: mongodb/mongodb-mcp-server:0.2.0
    environment:
      - MDB_MCP_CONNECTION_STRING=mongodb://user:password@shard-00-00.somehost.tld:27017/somedb?ssl=true&replicaSet=test-shard-0&authSource=admin&retryWrites=true&w=majority
      - MDB_MCP_READ_ONLY=true
      - MDB_MCP_TRANSPORT=http
      - MDB_MCP_HTTP_HOST=0.0.0.0
      - MDB_MCP_HTTP_PORT=3000
    ports:
      - "127.0.0.1:3000:3000"
```
